### ISSUE TITLE
EasyAbp.PrivateMessaging.Authorization.PrivateMessagingPermissionDefinitionProvider.Define(IPermissionDefinitionContext context)

### ISSUE THREAD

**Issue by DUWENINK** [EasyAbp/PrivateMessaging#12]
我按照 https://www.cnblogs.com/shanyou/p/12536988.html 这个教程完全安装了 最终却出现 

![image](https://user-images.githubusercontent.com/16337239/78985059-6893a100-7b5a-11ea-9b60-5a5f1305ba46.png)

**Comment by gdlcf88** [comment]
Hi, this doesn't solve the problem, please provide a git repository or try again by yourself.

**Comment by cicna** [comment]
我的也出现了，可能是没有设置权限？
看到文档里有这个说明：
Add permissions to the roles you want.

但不知道在哪里设置？

**Comment by gdlcf88** [comment]
I cannot reproduce your problems, but I guess it may be caused by the module ABP framework version. Please try the latest release: https://github.com/EasyAbp/PrivateMessaging/releases/latest

**Comment by cicna** [comment]
Thank you. After the upgrade, it is ready to use

**Comment by DUWENINK** [comment]
> Thank you. After the upgrade, it is ready to use

OK ,i will try it ,thank you!
