### ISSUE TITLE
引入模块后，未加载出来 私信模块

### ISSUE THREAD

**Issue by RyanOvO** [EasyAbp/PrivateMessaging#16]
![image](https://user-images.githubusercontent.com/31231960/82747362-a840e000-9dca-11ea-8d48-cbd09f90dfc4.png)
按照 手动安装指引引入后，数据库中有私信模块相关的表，但是启动时未能加载出来模块。
![image](https://user-images.githubusercontent.com/31231960/82747396-e807c780-9dca-11ea-8691-cb8f65eaf727.png)

**Comment by gdlcf88** [comment]
Please check the dependency of the Web module.
