### ISSUE TITLE
Add Extraproperties to PmUserDto

### ISSUE THREAD

**Issue by slarkerino** [EasyAbp/PrivateMessaging#35]
Is it possible to add Extraproperties to PmUserDto. In most use cases, we may want to display extra information such as avatar of a user.

**Comment by gdlcf88** [comment]
I'm afraid not. You can't get extra properties from the `Volo.Abp.Users.IUserData` since it's not extensible.

**Comment by gdlcf88** [comment]
However, app developers could override the `MapToDtoAndLoadMoreInfosAsync` method to load more extra properties for user data, so making the `PmUserDto` inherit `ExtensibleEntityDto<Guid>` is fine.
